import tkinter as tk
root=tk.Tk()
frame = tk.Frame(root,bg="lightgray",padx=6,pady=6)
frame.pack()
tk.Label(frame,text="Hello").pack()
var = tk.IntVar()
check = tk.Checkbutton(root,text=" I agree", variable=var)
check.pack()
var=tk.StringVar()
tk.Radiobutton(root,text="option 1", variable=var,value="1").pack()
tk.Radiobutton(root,text="option 2", variable=var,value="2").pack()
listbox = tk.Listbox(root,text="courses")
listbox.insert(1, "Python")
listbox.insert(2, "Java")
listbox.pack()
selected = listbox.get(listbox.curselection())
root.mainloop()